### ISSUE TITLE
please update a few homology converted pathways

### ISSUE THREAD

**Issue by egonw** [PathVisio/homology.mapper#1]
- [x] WP3193
- [x] WP3200
- [x] WP3237
- [x] WP3243 (has local changes)
- [x] WP3257 (has local changes which need to be checked in the original WP15 too)
- [x] WP3282
- [x] WP3940 (at least this one has some important changes by @DeniseSl22)

**Comment by DeniseSl22** [comment]
Yeah, for PW3940, I added the side branch for the Directed Small Molecules subnetwork, and I added some IDs for the NAR paper, since we wanted to have a low number of not annotated metabolites in Homo Sapiens Pathways... Overlooked that it was Homology converted, sorry about that!

**Comment by egonw** [comment]
After discussing with Tina, we have set out checks for all pathways here:

- [WP3193](https://github.com/wikipathways/wikipathways.org/issues/39)
- [WP3200](https://github.com/wikipathways/wikipathways.org/issues/40)
- [WP3237](https://github.com/wikipathways/wikipathways.org/issues/41)
- [WP3243](https://github.com/wikipathways/wikipathways.org/issues/42)
- [WP3257](https://github.com/wikipathways/wikipathways.org/issues/43)
- [WP3282](https://github.com/wikipathways/wikipathways.org/issues/44)
- [WP3940](https://github.com/wikipathways/wikipathways.org/issues/45)

**Comment by mkutmon** [comment]
Great! Is there a reason why you added the new issues for each pathway to the wikipathways.org repo and not the homology.mapper repo? Not a problem - I was just wondering.

**Comment by egonw** [comment]
I added one for each because then you can easily assign that one pathway to yourself, to indicate you're working on it.

**Comment by mkutmon** [comment]
Yes but it's in a different github repository - but I think that was an accident :). No worries.

**Comment by egonw** [comment]
Ah, that I did because these are basically WP.org curation issues... nothing to do with the convertor being wrong or so... right?

**Comment by DeniseSl22** [comment]
I would like to tick the box for WP3940, but I'm not allowed... So I think this is something the creator of this issue can only perform?

**Comment by egonw** [comment]
@mkutmon. it's up to you now...

**Comment by mkutmon** [comment]
- [x] WP3193 <- WP1533 (Homo sapiens to Bos taurus)
- [x] WP3200 <- WP2526 (Homo sapiens to Bos taurus)
- [x] WP3237 <- WP1981 (Homo sapiens to Bos taurus)
- [x] WP3243 <- WP2447 (Homo sapiens to Bos taurus)
- [x] WP3257 <- WP15 (Homo sapiens to Bos taurus)
- [x] WP3282 <- WP2583 (Homo sapiens to Bos taurus)
- [x] WP3940 <- WP1770 (Mus musculus to Homo sapiens)

**Comment by mkutmon** [comment]
done
