### ISSUE TITLE
a few more pathways that can be updated

### ISSUE THREAD

**Issue by egonw** [PathVisio/homology.mapper#2]
- [x] WP1033 (no edits since the last conversion)
- [x] WP1075 (has three edits by me, which need checking in original WP176)

**Comment by mkutmon** [comment]
@egonw did you already check WP1075?

**Comment by egonw** [comment]
I had not yet, but just did. Sorry, this one got lost on my radar. It looks good to go.

**Comment by mkutmon** [comment]
both updated now.
